---
title: "First GitPage"
date: 2019-09-05
---
theme: minima
title: My first GitPage 
author: JoshDGarton
email: Josh.d.garton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is the first GitPage i have made as part of self learning on Git

# social links
twitter_username: @wolf1790
github_username:  JoshDGarton

show_excerpts: true # set to false to remove excerpts on the homepage
